name: Joycon2BLEReceiver
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: 10.13
  createIntermediateGroups: true
  useTabs: false
  indentWidth: 4
  tabWidth: 4

targets:
  Joycon2BLEReceiver:
    type: application
    platform: macOS
    sources:
      - src
    settings:
      base:
        CLANG_CXX_LANGUAGE_STANDARD: c++17
        CLANG_CXX_LIBRARY: libc++
        MACOSX_DEPLOYMENT_TARGET: 10.13
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_ENTITLEMENTS: ""
        INFOPLIST_FILE: Joycon2forMac-Info.plist
    dependencies:
      - framework: CoreBluetooth.framework
      - framework: Foundation.framework
      - framework: AppKit.framework
    prebuildScripts:
      - name: Swift Version Check
        script: |
          echo "Building Joycon2BLEReceiver for macOS"